import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import AboutContent from '../components/AboutContent'

export default function About () {
    return (
<div>
      <Head>
        <title>Narma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <Navbar/>
      <AboutContent/>
      

    </div>
        





    )
}

