import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/index.module.css'
import React, { useState } from "react";


const Homepage = () => {
    const [style, setStyle] = useState(styles.audioPlayer);

    const changeStyle = () => {
        if (style==styles.audioPlayer){
        setStyle(styles.dropdownPlayer)};
        if (style==styles.dropdownPlayer){
        setStyle(styles.audioPlayer)}
        
    }

  return (
      <div className={styles.pageContainer}>
      <Head>
        <title>Cult Trip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
        {/* release 1 */}
          <div className={styles.Release}>
            <h2 className={styles.releaseTitle}>CT007
            
                <input className={styles.CT007toggle} type="checkbox"/>
                <label htmlFor={styles.CT007toggle}></label>
            </h2>
            <content className={styles.CT007Content}>
                <div className={styles.songContainer}>
                    <div className={styles.trackContainer} onClick={changeStyle}>
                        <audio controls className={style} src="/TEX86.mp3">
                            {/* <source src="/TEX86.mp3" type = "audio/mpeg"/> */}
                        </audio>
                        
                        <div className={styles.trackText}>
                            <h4>You'll Never Get Rich</h4>
                        </div>
                        
                    </div>
                    <div className={styles.trackContainer}>
                        <audio controls className={style}>
                            <source src="" type = "audio/mpeg"/>
                        </audio>
                        <div className={styles.trackText}>
                                <h4>Death by Dole</h4>
                        </div>
                    </div>
                </div>
                <div className={styles.artworkContainer}>
                    <svg  src=""/>
                </div>
            </content>
          </div>
        {/* Release 2 */}
        <div className={styles.Release}>
            <h2 className={styles.releaseTitle}>CT006</h2>
            <content className={styles.CT006Content}>
                <div className={styles.songContainer}>
                    <div className={styles.trackContainer} onClick={changeStyle}>
                        <audio controls className={style} src="/TEX86.mp3">
                            {/* <source src="/TEX86.mp3" type = "audio/mpeg"/> */}
                        </audio>
                        
                        <div className={styles.trackText}>
                            <h4>Track One</h4>
                        </div>
                        
                    </div>
                    <div className={styles.trackContainer}>
                        <audio controls className={styles.audioPlayer}>
                            <source src="" type = "audio/mpeg"/>
                        </audio>
                        <div className={styles.trackText}>
                                <h4>Track Two</h4>
                        </div>
                    </div>
                </div>
                <div className={styles.artworkContainer}>
                    <svg  src=""/>
                </div>
            </content>
          </div>       
        {/*closed page container*/}
      </div>
     

  );

};

export default Homepage;